Prefix: '&7[&b&nFreezer23&7]'
cmderror: ' &eUsage: &c/freeze <player>'
SoloJugador: '&bThis command must be executed as player!'
MsgCongelado1: '  &b&lYOU WERE FROZEN BY AN ADMIN!'
MsgCongelado2: '     &eYou have 2 minutes to join TS3!'
MsgCongelado3: '              &c&lTS.LAYTEN.NET'
PlayerCongelado: '&b&lThe player was frozen!'
MsgMoveCongelado: '&c&lOh, You can't move!'
MsgDescongelado: '        &a&lYOU ARE NOW UNFROZEN'
playercmd: '&ePlease, specify a player'
permission: '&c&nYou don't have permission to execute this command'
Error: '&4&lError'
